class_name GameConfigManager extends Resource

@export var game_config : GameConfig = null


func apply_game_config() -> void:
	
	GLOBALS.LEVEL_SECS_BEFORE_AUTHORITIES_ARRIVE = game_config.LEVEL_SECS_BEFORE_AUTHORITIES_ARRIVE
	
	GLOBALS.SHIP_MAX_HEALTH = game_config.SHIP_MAX_HEALTH
	GLOBALS.SHIP_MINIMUM_BOUNCE_SPEED = game_config.SHIP_MINIMUM_BOUNCE_SPEED
	
	GLOBALS.SHIP_ROTATION_SPEED = game_config.SHIP_ROTATION_SPEED
	GLOBALS.SHIP_ROTATION_CHANGE_RATE = game_config.SHIP_ROTATION_CHANGE_RATE
	GLOBALS.SHIP_BOOST_ROTATION_CHANGE_RATE = game_config.SHIP_BOOST_ROTATION_CHANGE_RATE
	GLOBALS.SHIP_ROTATION_ACCELERATION = game_config.SHIP_ROTATION_ACCELERATION
	
	GLOBALS.SHIP_FORWARD_SPEED = game_config.SHIP_FORWARD_SPEED
	GLOBALS.SHIP_FORWARD_CHANGE_RATE = game_config.SHIP_FORWARD_CHANGE_RATE
	GLOBALS.SHIP_BACK_SPEED = game_config.SHIP_BACK_SPEED
	GLOBALS.SHIP_BACK_CHANGE_RATE = game_config.SHIP_BACK_CHANGE_RATE
	GLOBALS.SHIP_NEUTRAL_CHANGE_RATE = game_config.SHIP_NEUTRAL_CHANGE_RATE
	GLOBALS.SHIP_BOOST_SPEED = game_config.SHIP_BOOST_SPEED
	GLOBALS.SHIP_BOOST_CHANGE_RATE = game_config.SHIP_BOOST_CHANGE_RATE
	
	
	GLOBALS.INVENTORY_CHANCE_TO_OPEN_ON_DAMAGE = game_config.INVENTORY_CHANCE_TO_OPEN_ON_DAMAGE
	
	GLOBALS.INVENTORY_MINIMUM_GRAB_DISTANCE = game_config.INVENTORY_MINIMUM_GRAB_DISTANCE
	GLOBALS.INVENTORY_SHIP_FORCE = game_config.INVENTORY_SHIP_FORCE
	GLOBALS.INVENTORY_RANDOM_FORCE = game_config.INVENTORY_RANDOM_FORCE
	GLOBALS.INVENTORY_JOLT_FORCE = game_config.INVENTORY_JOLT_FORCE
	GLOBALS.INVENTORY_JOLT_FORCE_REDUCTION = game_config.INVENTORY_JOLT_FORCE_REDUCTION
	GLOBALS.INVENTORY_DRAG_FORCE = game_config.INVENTORY_DRAG_FORCE
	GLOBALS.INVENTORY_RELEASE_FORCE = game_config.INVENTORY_RELEASE_FORCE
	
	GLOBALS.INVENTORY_CAMERA_TILT_STRENGTH = game_config.INVENTORY_CAMERA_TILT_STRENGTH
	GLOBALS.INVENTORY_CAMERA_TILT_SPEED = game_config.INVENTORY_CAMERA_TILT_SPEED
	GLOBALS.INVENTORY_CAMERA_PAN_STRENGTH = game_config.INVENTORY_CAMERA_PAN_STRENGTH
	GLOBALS.INVENTORY_CAMERA_PAN_SPEED = game_config.INVENTORY_CAMERA_PAN_SPEED
