class_name GameConfigManager extends Resource

@export var game_config : GameConfig = null


func apply_game_config() -> void:
	
	GLOBALS.SHIP_MAX_HEALTH = game_config.SHIP_MAX_HEALTH
	GLOBALS.SHIP_MINIMUM_BOUNCE_SPEED = game_config.SHIP_MINIMUM_BOUNCE_SPEED
	
	GLOBALS.SHIP_ROTATION_SPEED = game_config.SHIP_ROTATION_SPEED
	GLOBALS.SHIP_ROTATION_CHANGE_RATE = game_config.SHIP_ROTATION_CHANGE_RATE
	GLOBALS.SHIP_BOOST_ROTATION_CHANGE_RATE = game_config.SHIP_BOOST_ROTATION_CHANGE_RATE
	GLOBALS.SHIP_ROTATION_ACCELERATION = game_config.SHIP_ROTATION_ACCELERATION
	
	GLOBALS.SHIP_FORWARD_SPEED = game_config.SHIP_FORWARD_SPEED
	GLOBALS.SHIP_FORWARD_CHANGE_RATE = game_config.SHIP_FORWARD_CHANGE_RATE
	GLOBALS.SHIP_BACK_SPEED = game_config.SHIP_BACK_SPEED
	GLOBALS.SHIP_BACK_CHANGE_RATE = game_config.SHIP_BACK_CHANGE_RATE
	GLOBALS.SHIP_NEUTRAL_CHANGE_RATE = game_config.SHIP_NEUTRAL_CHANGE_RATE
	GLOBALS.SHIP_BOOST_SPEED = game_config.SHIP_BOOST_SPEED
	GLOBALS.SHIP_BOOST_CHANGE_RATE = game_config.SHIP_BOOST_CHANGE_RATE
	
